### ISSUE TITLE
./bin/handlebarspc is not found (from README instructions)

### ISSUE THREAD

**Issue by dmitris** [yahoo/context-parser-handlebars#6]
Trying to follow the installation instructions in an empty directory - getting an error:
```
$ npm install context-parser-handlebars && ./bin/handlebarspc foo.hb
context-parser-handlebars@1.0.1 node_modules/context-parser-handlebars
├── xss-filters@1.0.4
├── debug@2.1.1 (ms@0.6.2)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
└── context-parser@1.0.0
-bash: ./bin/handlebarspc: No such file or directory
```

I believe we shoud explicitly put ```./node_modules/context-parser-handlebars/bin/handlebarspc <handlebars template file>``` in README.md to spare users this error.

**Comment by adon-at-work** [comment]
I think we need something like this:
https://github.com/adon-at-work/context-parser-handlebars/commit/1639a3576438df6c2a5b3a6ab6e1fe48ce1b37d9

**Comment by adon-at-work** [comment]
docs:
- https://docs.npmjs.com/files/package.json#bin
- https://docs.npmjs.com/files/package.json#preferglobal

**Comment by adon-at-work** [comment]
and thus the README should be changed as:
~~./bin/~~`handlebarspc <handlebars template file>`

**Comment by dmitris** [comment]
Then you would want a global install - ```npm install -g context-parser-handlebars```, right?  That should work.

Compare http://handlebarsjs.com/precompilation.html ("Using the -g flag installs the package globally, so it can be used in any project.")

**Comment by adon-at-work** [comment]
yes. let's get inlined with the handlebars approach. i'll reject your PR, and make a new one.
